# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://deep-diver.github.io/csp_test_lib/"

git_url = "https://github.com/deep-diver/csp_test_lib/tree/master/"

def custom_doc_links(name): return None
